import { z } from "zod";
import { CHAIN_ID_TO_GATEWAY_URL } from "../chainMapping";

export const univ3Schema = z.object({
  // Network configuration
  chainId: z.number().min(1, "Chain ID is required").refine(
    (chainId) => chainId in CHAIN_ID_TO_GATEWAY_URL,
    { message: "Invalid chain ID. Please select a supported chain." }
  ),
  gatewayUrl: z.string().url("Gateway URL must be a valid URL").optional(),
  rpcUrl: z.string().optional(),
  finality: z.number().min(1, "Finality must be at least 1").optional().default(75),
  
  // Range configuration
  // fromBlock is optional for chains with scan support (auto-fetched), required for others
  fromBlock: z.number().min(0, "From block must be positive").optional(),
  toBlock: z.number().optional(),
  
  // Sink configuration (handled automatically in backend)
  csvPath: z.string().min(1, "CSV path is required").default("univ3-new.csv").optional(),
  enableStdout: z.boolean().default(true).optional(),
  enableAbsinthe: z.boolean().default(true).optional(),
  
  // General configuration
  flushIntervalHours: z.number().min(1, "Flush interval must be at least 1 hour").optional().default(48),
  
  // Pool address - only field user needs to enter
  poolAddress: z.string().regex(/^0x[a-fA-F0-9]{40}$/, "Must be a valid Ethereum address"),
  
  // These will be auto-generated by backend
  swaps: z.array(z.object({
    params: z.object({
      factoryAddress: z.string(),
      nonFungiblePositionManagerAddress: z.string(),
      poolAddress: z.string(),
    }),
    assetSelectors: z.object({
      swapLegAddress: z.string(),
    }),
    pricing: z.object({
      kind: z.literal("coingecko"),
      id: z.string(),
    }),
  })).optional(),
});

export type Univ3Config = z.infer<typeof univ3Schema>;

// Field definitions for the form
export const univ3Fields = [
  // Network fields
  { name: "chainId", label: "Chain", type: "select", options: [1, 137, 42161, 8453, 10, 43111, 56, 43114, 143] },
  { name: "finality", label: "Finality", type: "number", placeholder: "75" }, // In advanced options
  
  // Range fields
  { name: "fromBlock", label: "From Block", type: "number", placeholder: "507517" },
  { name: "toBlock", label: "To Block (optional)", type: "number", placeholder: "2524976" }, // In advanced options
  
  // General fields (moved to advanced options)
  { name: "flushIntervalHours", label: "Flush Interval (hours)", type: "number", placeholder: "48" },
] as const;
